import React from 'react';
// --- hr-tokens.jsx ---
// Design tokens + i18n for HR Portal

const HR_THEMES = {
  light: {
    name: 'Light',
    isDark: false,
    bg: '#F6F3EC',
    page: '#EFEADD',
    panel: '#FFFFFF',
    panelAlt: '#FBF8F1',
    panelSunk: '#F1ECDE',
    border: 'rgba(20,45,42,0.09)',
    borderStrong: 'rgba(20,45,42,0.16)',
    divider: 'rgba(20,45,42,0.06)',
    text: '#0D2321',
    textMid: '#3B4F4C',
    textMuted: 'rgba(13,35,33,0.58)',
    textFaint: 'rgba(13,35,33,0.38)',
    ink: '#0D2321',
    accent: '#1F5A4E',       // deep green
    accentInk: '#FFFFFF',
    accentSoft: 'rgba(31,90,78,0.10)',
    warm: '#C27A38',          // amber in light ctx
    warmSoft: 'rgba(194,122,56,0.12)',
    positive: '#2E7D5E',
    caution:  '#B4861F',
    danger:   '#A2432B',
    info:     '#3F6B83',
    series: ['#1F5A4E', '#C27A38', '#3F6B83', '#A2432B', '#6D4F8F'],
    sidebarBg: '#0E2A26',
    sidebarText: 'rgba(245,241,232,0.72)',
    sidebarActive: '#F5B544',
    sidebarActiveText: '#1A1206',
    sidebarMark: '#F5F1E8',
    shadowSm: '0 1px 2px rgba(13,35,33,0.05)',
    shadowMd: '0 6px 18px rgba(13,35,33,0.06)',
  },
  dark: {
    name: 'Dark',
    isDark: true,
    bg: '#0B1F1C',
    page: '#0A1B19',
    panel: '#112B27',
    panelAlt: '#143532',
    panelSunk: '#0E2522',
    border: 'rgba(245,241,232,0.07)',
    borderStrong: 'rgba(245,241,232,0.14)',
    divider: 'rgba(245,241,232,0.05)',
    text: '#F5F1E8',
    textMid: 'rgba(245,241,232,0.82)',
    textMuted: 'rgba(245,241,232,0.58)',
    textFaint: 'rgba(245,241,232,0.34)',
    ink: '#F5F1E8',
    accent: '#F5B544',        // amber
    accentInk: '#1A1206',
    accentSoft: 'rgba(245,181,68,0.14)',
    warm: '#F5B544',
    warmSoft: 'rgba(245,181,68,0.14)',
    positive: '#6FC79B',
    caution:  '#F5B544',
    danger:   '#E27F6A',
    info:     '#8FB3C9',
    series: ['#F5B544', '#6FC79B', '#8FB3C9', '#E27F6A', '#B9A0D9'],
    sidebarBg: '#081714',
    sidebarText: 'rgba(245,241,232,0.68)',
    sidebarActive: '#F5B544',
    sidebarActiveText: '#1A1206',
    sidebarMark: '#F5F1E8',
    shadowSm: '0 1px 2px rgba(0,0,0,0.25)',
    shadowMd: '0 10px 30px rgba(0,0,0,0.4)',
  },
};

const DENSITY = {
  compact:    { row: 40, cellPadY: 8,  cardPad: 16, gap: 14, kpiPad: 16 },
  comfortable:{ row: 52, cellPadY: 12, cardPad: 20, gap: 20, kpiPad: 22 },
};

const HR_STRINGS = {
  en: {
    dashboard: 'Dashboard', teams: 'Teams', people: 'People',
    safety: 'Safety', content: 'Content', challenges: 'Challenges',
    broadcasts: 'Broadcasts', reports: 'Reports', settings: 'Settings',
    overview: 'Overview',
    tenant: 'Nile Group',
    search: 'Search teams, people, content…',
    today: 'Today', week: 'This week', month: 'This month', quarter: 'This quarter',
    exportPdf: 'Export report',
    wellbeingIndex: 'Wellbeing Index',
    weeklyActive: 'Weekly active',
    atRiskTeams: 'At-risk teams',
    safetyFlags: 'Safety flags',
    vsPrior: 'vs. prior period',
    seven: '7d', thirty: '30d', ninety: '90d',
    wellbeingTrends: 'Wellbeing trends',
    sleep: 'Sleep', stress: 'Stress', energy: 'Energy', mood: 'Mood',
    teamBreakdown: 'Team breakdown',
    filterAll: 'All departments',
    team: 'Team', head: 'Head', size: 'Size', index: 'Index', trend: 'Trend', risk: 'Risk',
    safetyQueue: 'Safety escalation queue',
    activeBroadcasts: 'Broadcasts',
    draftPost: 'New broadcast',
    contentPins: 'Pinned for your org',
    activeChallenges: 'Active challenges',
    newChallenge: 'New challenge',
    lastUpdated: 'Last updated',
    rolesSeats: 'Seats · Roles',
    seatsUsed: 'seats active of',
    density: 'Density', layout: 'Layout', chartStyle: 'Chart style', theme: 'Theme', language: 'Language',
    tweaks: 'Tweaks',
    low: 'Low', med: 'Elevated', high: 'High',
    resolved: 'Resolved', open: 'Open', review: 'Review',
    viewAll: 'View all',
    peopleYouManage: 'People you manage',
    greeting: 'Good morning, Hana',
    subGreet: 'Here\u2019s your org\u2019s wellbeing snapshot for',
    actions: 'Actions',
    notifs: 'Notifications',
    engagement: 'Engagement',
    downTrend: 'Down', upTrend: 'Up', flat: 'Flat',
    nudge: 'Send nudge', message: 'Message', viewProfile: 'View profile',
  },
  ar: {
    dashboard: 'لوحة التحكم', teams: 'الفرق', people: 'الأشخاص',
    safety: 'السلامة', content: 'المحتوى', challenges: 'التحديات',
    broadcasts: 'البث', reports: 'التقارير', settings: 'الإعدادات',
    overview: 'نظرة عامة',
    tenant: 'مجموعة النيل',
    search: 'ابحث عن الفرق، الأشخاص، المحتوى…',
    today: 'اليوم', week: 'هذا الأسبوع', month: 'هذا الشهر', quarter: 'هذا الربع',
    exportPdf: 'تصدير التقرير',
    wellbeingIndex: 'مؤشر الرفاهية',
    weeklyActive: 'النشاط الأسبوعي',
    atRiskTeams: 'الفرق المعرضة للخطر',
    safetyFlags: 'إشارات السلامة',
    vsPrior: 'مقارنة بالفترة السابقة',
    seven: '٧ي', thirty: '٣٠ي', ninety: '٩٠ي',
    wellbeingTrends: 'اتجاهات الرفاهية',
    sleep: 'النوم', stress: 'التوتر', energy: 'الطاقة', mood: 'المزاج',
    teamBreakdown: 'تفاصيل الفرق',
    filterAll: 'كل الأقسام',
    team: 'الفريق', head: 'القائد', size: 'العدد', index: 'المؤشر', trend: 'الاتجاه', risk: 'المخاطر',
    safetyQueue: 'قائمة تصعيد السلامة',
    activeBroadcasts: 'البث',
    draftPost: 'بث جديد',
    contentPins: 'مثبَّت لمنظمتك',
    activeChallenges: 'تحديات نشطة',
    newChallenge: 'تحدي جديد',
    lastUpdated: 'آخر تحديث',
    rolesSeats: 'المقاعد · الأدوار',
    seatsUsed: 'مقعد نشط من',
    density: 'الكثافة', layout: 'التخطيط', chartStyle: 'نمط الرسم', theme: 'المظهر', language: 'اللغة',
    tweaks: 'التعديلات',
    low: 'منخفض', med: 'مرتفع', high: 'عالٍ',
    resolved: 'تم الحل', open: 'مفتوح', review: 'للمراجعة',
    viewAll: 'عرض الكل',
    peopleYouManage: 'الأشخاص الذين تديرهم',
    greeting: 'صباح الخير، هناء',
    subGreet: 'لمحة عن رفاهية منظمتك ',
    actions: 'إجراءات',
    notifs: 'الإشعارات',
    engagement: 'المشاركة',
    downTrend: 'منخفض', upTrend: 'مرتفع', flat: 'ثابت',
    nudge: 'إرسال تحفيز', message: 'رسالة', viewProfile: 'عرض الملف',
  },
};

Object.assign(window, { HR_THEMES, DENSITY, HR_STRINGS });

export { HR_THEMES, DENSITY, HR_STRINGS };
