-- Personalized insights cache (generated by Edge Function, read by app)
CREATE TABLE public.user_insights (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  company_id  UUID NOT NULL REFERENCES public.companies(id),
  metric      TEXT NOT NULL CHECK (metric IN ('sleep','stress','energy','mood','overall')),
  icon        TEXT NOT NULL DEFAULT 'sparkle',
  tone        TEXT NOT NULL DEFAULT 'info' CHECK (tone IN ('positive','info','neutral','warning')),
  title_en    TEXT NOT NULL,
  title_ar    TEXT,
  body_en     TEXT NOT NULL,
  body_ar     TEXT,
  valid_until DATE NOT NULL DEFAULT (current_date + 7),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_insights_user ON public.user_insights(user_id, valid_until DESC);

-- RLS: own insights only
ALTER TABLE public.user_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "insights_own" ON public.user_insights
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "service_role_insights" ON public.user_insights
  USING (auth.role() = 'service_role');
